spring:
  application:
    name: future-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        fail-fast: false
      config:
        server-addr: localhost:8848
        access-key: VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg
        import-check:
          enabled: false
      username: nacos
      password: xiacf17.
server:
  port: 7778
# 启用追踪
management:
  tracing:
    sampling:
      probability: 1.0           # 等价于 sleuth.sampler.probability
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans   # 等价于 zipkin.base-url
