spring:
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        fail-fast: false
      config:
        server-addr: localhost:8848
        access-key: VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg
        import-check:
          enabled: false
      username: nacos
      password: xiacf17.
    gateway:
      server:
        webflux:
          routes:
            - id: future-service
              uri: lb://future-service
              predicates:
                - Path=/future/**
              filters:
                - StripPrefix=1
                - name: Intercept
                  args:
                    message: "hello"
#           配置为全局默认过滤器：
#          default-filters:
#            - name: Intercept
#              args:
#                message: "hello"
server:
  port: 7777
# 启用追踪
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # 采样率设置为100%
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
